attack_vector :; @forge test --contracts /Users/sallywang/attackreplay/nomadattack/attack_vector.sol -vvvv
unit_test_contrived :; @forge test --contracts /Users/sallywang/attackreplay/nomadattack/unit_test_contrived.sol -vvvv

